import type { Metadata } from 'next'
import { Fraunces, Hind_Siliguri, IBM_Plex_Mono } from 'next/font/google'
import 'katex/dist/katex.min.css'
import './globals.css'
import ThemeProvider from '@/Component/Provider/ThemeProvider'
import I18nProvider from '@/Component/Provider/I18nProvider'
import { Toaster } from 'react-hot-toast'

const fraunces = Fraunces({
  variable: '--font-fraunces',
  subsets: ['latin'],
  weight: ['400', '500', '600'],
})

const hindSiliguri = Hind_Siliguri({
  variable: '--font-hind-siliguri',
  subsets: ['latin', 'bengali'],
  weight: ['400', '500', '600', '700'],
})

const plexMono = IBM_Plex_Mono({
  variable: '--font-plex-mono',
  subsets: ['latin'],
  weight: ['400', '500'],
})

export const metadata: Metadata = {
  title: 'Sharif Academy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${hindSiliguri.variable} ${plexMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground transition-colors duration-200">
        <I18nProvider>
          <ThemeProvider>{children}</ThemeProvider>
          <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
              duration: 4000,
              style: {
                borderRadius: '10px',
              },
            }}
          />
        </I18nProvider>
      </body>
    </html>
  )
}
