import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'katex/dist/katex.min.css'
import "./globals.css";
import ThemeProvider from "@/Component/Provider/ThemeProvider";
import I18nProvider from "@/Component/Provider/I18nProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sharif Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col dark:bg-slate-900 bg-white text-slate-900 dark:text-slate-100 transition-colors duration-200">
        <I18nProvider>
          <ThemeProvider>{children}</ThemeProvider>
          <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
              duration: 4000,
              style: {
                borderRadius: '10px',
              },
            }}
          />
        </I18nProvider>
      </body>
    </html>
  )
}
